run:
  wandb_tags: ["batch-size-variations"]

optimizer:
  lr: 6.0e-3

training:
  batch_size: 2
  max_steps: 640000
  eval_interval: 10_000_000
  eval_steps: 1
  eval_batch_size: 2
  checkpoint_interval: 640000
  lr_max: 6.0e-3
  warmup_ratio: 0.05 