run:
  wandb_tags: ["batch-size-variations"]

optimizer:
  lr: 1.0e-3

training:
  batch_size: 4
  max_steps: 320_000
  eval_interval: 10_000
  eval_steps: 100
  eval_batch_size: 4
  checkpoint_interval: 320_000
  lr_max: 1.0e-3
  warmup_ratio: 0.1 