run:
  wandb_tags: ["batch-size-variations"]

optimizer:
  lr: 8.0e-3

training:
  batch_size: 512
  max_steps: 2500
  eval_interval: 10_000_000
  eval_steps: 1
  eval_batch_size: 512
  checkpoint_interval: 2500
  lr_max: 8.0e-3
  warmup_ratio: 0.05 